# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: forca.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66orca.proto\x12\x05\x66orca\"&\n\x0fJoinGameRequest\x12\x13\n\x0bplayer_name\x18\x01 \x01(\t\"G\n\x10JoinGameResponse\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07players\x18\x03 \x03(\t\"%\n\x10StartGameRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\"5\n\x11StartGameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"7\n\x12GuessLetterRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x0e\n\x06letter\x18\x02 \x01(\t\"Z\n\x13GuessLetterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x63orrect\x18\x02 \x01(\x08\x12\x11\n\tgame_over\x18\x03 \x01(\x08\x12\x0e\n\x06points\x18\x04 \x01(\x05\"(\n\x13GetGameStateRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\"\xbc\x01\n\x14GetGameStateResponse\x12\x14\n\x0c\x63urrent_word\x18\x01 \x01(\t\x12\x15\n\rattempts_left\x18\x02 \x01(\x05\x12\x17\n\x0fguessed_letters\x18\x03 \x03(\t\x12\x16\n\x0e\x63urrent_player\x18\x04 \x01(\t\x12\"\n\x06scores\x18\x05 \x03(\x0b\x32\x12.forca.PlayerScore\x12\x11\n\tgame_over\x18\x06 \x01(\x08\x12\x0f\n\x07message\x18\x07 \x01(\t\"1\n\x0bPlayerScore\x12\x13\n\x0bplayer_name\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x05\x32\x93\x02\n\x05\x46orca\x12;\n\x08JoinGame\x12\x16.forca.JoinGameRequest\x1a\x17.forca.JoinGameResponse\x12>\n\tStartGame\x12\x17.forca.StartGameRequest\x1a\x18.forca.StartGameResponse\x12\x44\n\x0bGuessLetter\x12\x19.forca.GuessLetterRequest\x1a\x1a.forca.GuessLetterResponse\x12G\n\x0cGetGameState\x12\x1a.forca.GetGameStateRequest\x1a\x1b.forca.GetGameStateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'forca_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINGAMEREQUEST']._serialized_start=22
  _globals['_JOINGAMEREQUEST']._serialized_end=60
  _globals['_JOINGAMERESPONSE']._serialized_start=62
  _globals['_JOINGAMERESPONSE']._serialized_end=133
  _globals['_STARTGAMEREQUEST']._serialized_start=135
  _globals['_STARTGAMEREQUEST']._serialized_end=172
  _globals['_STARTGAMERESPONSE']._serialized_start=174
  _globals['_STARTGAMERESPONSE']._serialized_end=227
  _globals['_GUESSLETTERREQUEST']._serialized_start=229
  _globals['_GUESSLETTERREQUEST']._serialized_end=284
  _globals['_GUESSLETTERRESPONSE']._serialized_start=286
  _globals['_GUESSLETTERRESPONSE']._serialized_end=376
  _globals['_GETGAMESTATEREQUEST']._serialized_start=378
  _globals['_GETGAMESTATEREQUEST']._serialized_end=418
  _globals['_GETGAMESTATERESPONSE']._serialized_start=421
  _globals['_GETGAMESTATERESPONSE']._serialized_end=609
  _globals['_PLAYERSCORE']._serialized_start=611
  _globals['_PLAYERSCORE']._serialized_end=660
  _globals['_FORCA']._serialized_start=663
  _globals['_FORCA']._serialized_end=938
# @@protoc_insertion_point(module_scope)
